#!/bin/bash

if [ "$(git rev-parse --abbrev-ref HEAD)" = "main" ]; then
    exit 0
fi

echo "Pre-commit hook started..."

CONFIG="version"

if [ ! -f "$CONFIG" ]; then
    echo "Config file not found!"
    exit 1
fi

CURRENT_VERSION=$(grep -Eo '^[0-9]+\.[0-9]+\.[0-9]+' "$CONFIG")
IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

PATCH=$((PATCH + 1))
NEW_VERSION="$MAJOR.$MINOR.$PATCH"

sed -i "s/^$CURRENT_VERSION\$/$NEW_VERSION/" "$CONFIG"

git add "$CONFIG"


